DEX-228 SDK references
skyflowapi/skyflow-go pull request #53
Opened 2023-07-17 12:24 UTC by shivkeshmadasu-skyflow

2023-08-09 22:53 UTC, manny-silva requested changes
Nits

2023-08-09 22:53 UTC, manny-silva commented on skyflow/client/client.go
> +// Represents a client instance to interact with Skyflow's vault API.
Represents a client instance that interacts with Skyflow's APIs.

2023-08-09 22:53 UTC, manny-silva commented on skyflow/client/token_utils.go
> +// Represents a utility structure for handling bearer token.
...for handling bearer tokens.

2023-08-09 22:53 UTC, manny-silva commented on skyflow/vaultapi/get_by_id.go
> +// Retrieves records using SkyflowID's.
"Skyflow IDs"

2023-08-09 22:53 UTC, manny-silva commented on skyflow/vaultapi/insert.go
> +// An interface for performing HTTP requests.
Interface for performing HTTP requests.

2026-06-16 11:22 UTC, Devesh-Skyflow commented
This PR is being closed as it is no longer relevant. Please re-open or raise a new PR if these changes are still needed.

2026-06-16 11:22 UTC, closed without merging